DROP TABLE IF EXISTS USER;

CREATE TABLE USER (USER_ID int(10) NOT NULL AUTO_INCREMENT,
                  USER_NAME varchar(30) NOT NULL,
                  USER_ADDRESS varchar(100) NOT NULL,
                  PRIMARY KEY (USER_ID));

INSERT INTO USER (USER_NAME, USER_ADDRESS) VALUES ('DHANANJAYA', 'BANGALORE');
INSERT INTO USER (USER_NAME, USER_ADDRESS) VALUES ('LIJARANI', 'BANGALORE');
INSERT INTO USER (USER_NAME, USER_ADDRESS) VALUES ('MADHUSMITA', 'BANGALORE');
INSERT INTO USER (USER_NAME, USER_ADDRESS) VALUES ('SASMITA', 'BHUBANESWAR');


-- CREATE PROCEDURE MANUALLY in SQL DB
/*

CREATE PROCEDURE FIND_USER_BY_ID(IN id INT)
BEGIN
SELECT * FROM USER WHERE USER_ID = id;
END


CREATE PROCEDURE COUNT_USER_BY_ADDRESS(IN user_addr VARCHAR(30), OUT count_out INT)
BEGIN
SELECT COUNT(*) into count_out from USER WHERE USER_ADDRESS = user_addr;
END

*/